export const GET_PLANET_DATA = 'GET_PLANET_DATA';
export const GET_PLANET_DATA_SUCCESS = 'GET_PLANET_DATA_SUCCESS';
export const GET_PLANET_DATA_FAILURE = 'GET_PLANET_DATA_FAILURE';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';